# Generated by Django 3.2.7 on 2021-09-16 13:22

import Accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Accounts.manager.UserManager()),
            ],
        ),
    ]
