# Generated by Django 3.1.7 on 2021-09-17 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Country Name', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='Team Name', max_length=255)),
                ('sports_type', models.CharField(help_text='Sport Type', max_length=255)),
                ('event', models.CharField(help_text='Event type', max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.country')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Medals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='Ranking')),
                ('gold', models.IntegerField(help_text='No. of Gold Medals')),
                ('silver', models.IntegerField(help_text='No. of Silver Medals')),
                ('bronze', models.IntegerField(help_text='No. of Bronze Medals')),
                ('total_medal', models.IntegerField(help_text='Total number of Medals')),
                ('total_medal_rank', models.IntegerField(help_text='Ranking based on No. of Medals received')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.country')),
            ],
            options={
                'db_table': 'medals',
            },
        ),
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Athlete Name', max_length=255)),
                ('sports', models.CharField(help_text='Sport Type', max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.country')),
            ],
            options={
                'db_table': 'athletes',
            },
        ),
    ]
