# Generated by Django 3.1.7 on 2021-09-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210917_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_type', models.CharField(help_text='Sport Type', max_length=255)),
                ('male', models.IntegerField(help_text='No. of Males')),
                ('female', models.IntegerField(help_text='No. of Females')),
                ('total', models.IntegerField(help_text='Total')),
            ],
            options={
                'db_table': 'sportsgender',
            },
        ),
    ]
