# Generated by Django 3.1.7 on 2021-09-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_sportsgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, help_text='OTP', max_length=20, null=True),
        ),
    ]
