# Generated by Django 3.2.7 on 2021-09-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20210921_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
